name: Code Format Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Check code format
        run: dotnet format cosmobot.sln --include Assets/Scripts/ --verify-no-changes --severity warn